import { MainPage } from "@/pages-fsd";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>ivi-clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://gambit-central.dfs.ivi.ru/dist/23.05.02_4ab9e116/storm/images/favicon/64.png"
        />
      </Head>
      <main>
        <MainPage />
      </main>
    </>
  );
}
